### ISSUE TITLE
Material Imba

### ISSUE THREAD

**Issue by najohnson** [koolamusic/awesome-imba#14]
**Is your feature request related to a problem? Please describe.**
Not a problem. I have a material ui library that I made in imba: https://github.com/nathanjohnson320/material-imba

**Describe the solution you'd like**
Would like material-imba added under the frameworks list if possible

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by koolamusic** [comment]
Lovely project
Thoughts : 
- On your docs page, you could make the Material Imba Text on the Navbar link back to the homepage. I think it provides a better user experience while navigating the docs.

Please create a pull request for the library under Toolkits and Framework
https://github.com/koolamusic/awesome-imba#toolkits-and-frameworks
