### ISSUE TITLE
Add Imba to sindresorhus/awesome

### ISSUE THREAD

**Issue by shapkarin** [koolamusic/awesome-imba#25]
Follow all awesome lists guidelines https://github.com/sindresorhus/awesome/pull/1591

for example we need to add @koolamusic email here like the instruction says: https://github.com/koolamusic/awesome-imba/blob/master/.github/CODE_OF_CONDUCT.md `[INSERT EMAIL ADDRESS]`

**Comment by shapkarin** [comment]
@koolamusic Maybe I can create some team email and share an access somehow with you..

**Comment by koolamusic** [comment]
My email is koolamusic@tecmie.com | I will use that

**Comment by koolamusic** [comment]
@shapkarin How are we on this ?

**Comment by shapkarin** [comment]
Hard to tell, I need some time to check all gramma but I'm not a native speaker. Also I think look  again and more closely to this list, maybe I can improve it somehow. Hope today I can find the time.

**Comment by koolamusic** [comment]
@all-contributors please add @shapkarin  for infrastructure, tests and code

**Comment by koolamusic** [comment]
@all-contributors please add @koolamusic  for code, doc, review and tool

**Comment by koolamusic** [comment]
@all-contributors please add @athif23 for code, doc

**Comment by koolamusic** [comment]
@all-contributors please add @konsumer for code, doc

**Comment by koolamusic** [comment]
@all-contributors add @somebee for code, doc, example

**Comment by koolamusic** [comment]
@all-contributors please ass @nathanjohnson320 for doc

**Comment by koolamusic** [comment]
@all-contributors please add @nathanjohnson320 for doc

**Comment by koolamusic** [comment]
@all-contributors please add @activestylus for example

**Comment by koolamusic** [comment]
@all-contributor please add @SamirHodzic for code, doc and example

**Comment by shapkarin** [comment]
Please, try to have a look closer to the list descriptions. It seems that list is still not so good at some points. I will also have a look at this week.

**Comment by shapkarin** [comment]
let me try too
@all-contributors please add @shapkarin for infrastructure, tests, code and example

Also as I can see it generate badge too, I thought it was someones mistake and replace it with githubs one

**Comment by shapkarin** [comment]
@all-contributors please add @shapkarin for infrastructure, tests, code, doc and example

**Comment by shapkarin** [comment]
@all-contributors please add @SamirHodzic for code, doc and example

**Comment by shapkarin** [comment]
@koolamusic I guess we need other issue for that commands but anyway

@all-contributors please add @konsumer for code, doc and example

**Comment by shapkarin** [comment]
@all-contributors please add @shapkarin for infrastructure, code, doc and example

**Comment by shapkarin** [comment]
not sure that I got what I [need to fix](https://github.com/sindresorhus/awesome/tree/gh-pages) but hope so

**Comment by shapkarin** [comment]
Guidelines - https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

**Comment by shapkarin** [comment]
It's merged
