### ISSUE TITLE
Hello World Imba instructions

### ISSUE THREAD

**Issue by shapkarin** [koolamusic/awesome-imba#47]
Can't find instructions for https://github.com/imba/hello-world-imba
I remember that I saw some..

**Comment by scanf** [comment]
@shapkarin maybe it's this one https://github.com/jiggneshhgohel/hello-world-imba

**Comment by shapkarin** [comment]
@scanf right, thanks

**Comment by shapkarin** [comment]
@scanf are you sure that provided instructions are for the [this project](https://github.com/imba/hello-world-imba)? I saw in repo description "Barebones Imba example with `instructions`" but can't find any references and projects are seems to be different a little.

**Comment by scanf** [comment]
Yeah they are different but still related. Hence I assumed that was what you were referring to.

If you can elaborate on what you mean by instructions. I can try to help but the official  readme has terse instructions on getting started with that example. Let me know if I misunderstood you.

**Comment by shapkarin** [comment]
@scanf thanks for clarify and also for the provided link, I have [added that link](https://github.com/koolamusic/awesome-imba/commit/762c01a656a9fc24479a56d4ea683875a9f9dceb#diff-04c6e90faac2675aa89e2176d2eec7d8R68) to other section.
