### ISSUE TITLE
Changes to add to the list of lists

### ISSUE THREAD

**Issue by shapkarin** [koolamusic/awesome-imba#7]
I create [pull request](https://github.com/sindresorhus/awesome/pull/1488) to the list of lists. But get that comment:

> Many entries do not have a description. They are not self explanatory for people that do not know the the language.
> Lacks of period at the end of many entries.
> Lack of table of content.
> How to "Feel free to share with us"?

**Comment by shapkarin** [comment]
I made some changes, so seems that's only need to add CONTRIBUTING.md

**Comment by shapkarin** [comment]
I added contributing. but I think that repo also needs a code-of-conduct.md 
example: https://github.com/sindresorhus/awesome/blob/master/code-of-conduct.md

**Comment by koolamusic** [comment]
made some review

**Comment by koolamusic** [comment]
Reviewing
